/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CanteensRouteImport } from './routes/canteens'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as PromosRouteImport } from './routes/promos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SellerRouteImport } from './routes/seller'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CanteenSlugRouteImport } from './routes/canteen.$slug'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteensRoute = CanteensRouteImport.update({
  id: '/canteens',
  path: '/canteens',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PromosRoute = PromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerRoute = SellerRouteImport.update({
  id: '/seller',
  path: '/seller',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CanteenSlugRoute = CanteenSlugRouteImport.update({
  id: '/canteen/$slug',
  path: '/canteen/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/canteens': typeof CanteensRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/promos': typeof PromosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller': typeof SellerRoute
  '/settings': typeof SettingsRoute
  '/canteen/$slug': typeof CanteenSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/canteens': typeof CanteensRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/promos': typeof PromosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller': typeof SellerRoute
  '/settings': typeof SettingsRoute
  '/canteen/$slug': typeof CanteenSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/canteens': typeof CanteensRoute
  '/cart': typeof CartRoute
  '/chat': typeof ChatRoute
  '/orders': typeof OrdersRoute
  '/promos': typeof PromosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seller': typeof SellerRoute
  '/settings': typeof SettingsRoute
  '/canteen/$slug': typeof CanteenSlugRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/canteens'
    | '/cart'
    | '/chat'
    | '/orders'
    | '/promos'
    | '/reset-password'
    | '/seller'
    | '/settings'
    | '/canteen/$slug'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/canteens'
    | '/cart'
    | '/chat'
    | '/orders'
    | '/promos'
    | '/reset-password'
    | '/seller'
    | '/settings'
    | '/canteen/$slug'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/canteens'
    | '/cart'
    | '/chat'
    | '/orders'
    | '/promos'
    | '/reset-password'
    | '/seller'
    | '/settings'
    | '/canteen/$slug'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  CanteensRoute: typeof CanteensRoute
  CartRoute: typeof CartRoute
  ChatRoute: typeof ChatRoute
  OrdersRoute: typeof OrdersRoute
  PromosRoute: typeof PromosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SellerRoute: typeof SellerRoute
  SettingsRoute: typeof SettingsRoute
  CanteenSlugRoute: typeof CanteenSlugRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteens': {
      id: '/canteens'
      path: '/canteens'
      fullPath: '/canteens'
      preLoaderRoute: typeof CanteensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promos': {
      id: '/promos'
      path: '/promos'
      fullPath: '/promos'
      preLoaderRoute: typeof PromosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller': {
      id: '/seller'
      path: '/seller'
      fullPath: '/seller'
      preLoaderRoute: typeof SellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canteen/$slug': {
      id: '/canteen/$slug'
      path: '/canteen/$slug'
      fullPath: '/canteen/$slug'
      preLoaderRoute: typeof CanteenSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  CanteensRoute: CanteensRoute,
  CartRoute: CartRoute,
  ChatRoute: ChatRoute,
  OrdersRoute: OrdersRoute,
  PromosRoute: PromosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SellerRoute: SellerRoute,
  SettingsRoute: SettingsRoute,
  CanteenSlugRoute: CanteenSlugRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
